### ISSUE TITLE
Project hourglass discs coordinates on the spinal cord

### ISSUE THREAD

**Issue by NathanMolinier** [spinalcordtoolbox/disc-labeling-hourglass#2]
## Description

Currently, the `sct_label_vertebrae` function used in the [spinalcordtoolbox](https://github.com/spinalcordtoolbox/spinalcordtoolbox)  output discs labels along the spinal cord, however, the hourglass is trained to output disc labels on the posterior tip of the discs.

**sct_label_vertebrae**       |  **hourglass**
:-------------------------:|:-------------------------:
<img width="321" alt="Capture d’écran 2023-03-22 à 18 11 13" src="https://user-images.githubusercontent.com/68945192/227050193-21b85acd-7a3a-4aa6-b779-f207fd99d318.png">  |  <img width="320" alt="Capture d’écran 2023-03-22 à 18 11 00" src="https://user-images.githubusercontent.com/68945192/227050165-0f8e9ce7-7ee1-495c-8f94-dff724c78f89.png">

## Issue

Therefore, to be fair in the results comparison, discs labels should all be projected along the spinal cord. Is there a way to do that currently in sct ? @jcohenadad @benjamindeleener 

## Related issue

[#3395](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3395#issue-894513626)

**Comment by jcohenadad** [comment]
> Therefore, to be fair in the results comparison, discs labels should all be projected along the spinal cord. Is there a way to do that currently in sct ? @jcohenadad @benjamindeleener

discussion thread: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3395

**Comment by NathanMolinier** [comment]
The new option `-project-centerline` is now available with the function `sct_label_utils`
