### ISSUE TITLE
Missing ground truth coordinates for `disc 1`

### ISSUE THREAD

**Issue by NathanMolinier** [spinalcordtoolbox/disc-labeling-hourglass#6]
## Description

For all the subjects, the disc 1 coordinate does not appear in the ground truth even when present in the original data, it seems that this coordinate was removed maybe unintentionally. Therefore, making the hourglass unable to identify this disc.

### Example
The first coordinate corresponds to sct_label_vertebrae, the second is the hourglass prediction and the third is the ground truth
<img width="417" alt="Capture d’écran 2023-03-29 à 13 12 52" src="https://user-images.githubusercontent.com/68945192/228616310-6d91bc64-7fdf-46ab-9fb8-1e415f7b3f30.png">

Here a screenshot of the same subject with the disc 1 coordinate
<img width="1280" alt="Capture d’écran 2023-03-29 à 13 14 20" src="https://user-images.githubusercontent.com/68945192/228616661-cc3998bf-6b08-403e-9f5b-6e6c352b6ab6.png">

**Comment by jcohenadad** [comment]
good catch! On that topic: I'm not sure how the other labels look like, but this C1 label looks a bit too inferior to my taste. What do you think @sandrinebedard @valosekj ?

**Comment by sandrinebedard** [comment]
> good catch! On that topic: I'm not sure how the other labels look like, but this C1 label looks a bit too inferior to my taste. What do you think @sandrinebedard @valosekj ?

I agree it is a bit too inferior!

**Comment by NathanMolinier** [comment]
The issue seems to be related to the function [mask2label](https://github.com/spinalcordtoolbox/disc-labeling-hourglass/blob/main/utils/data2array.py#L62-L84) in `utils/data2array.py`: [line 78](https://github.com/spinalcordtoolbox/disc-labeling-hourglass/blob/main/utils/data2array.py#L78)

Moreover, this function seems really complex for nothing. I might rewrite it using the method `getNonZeroCoordinates` available with the [Image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/master/spinalcordtoolbox/image.py#L248) object from [spinalcordtoolbox](https://github.com/spinalcordtoolbox/spinalcordtoolbox)
